//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.13 at 09:41:58 PM PDT 
//


package com.irets.datadownloader;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CityElem" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Cities", propOrder = {
    "cityElem"
})
@XmlRootElement(name = "Cities")
public class CitiesElemXML {

    @XmlElement(name = "City")
    protected List<CitiesElemXML.CityElem> cityElem;
    @XmlAttribute(name = "Count",required = true)
    protected BigInteger mcount;
    @XmlAttribute(name = "TotalCount",required = true)
    protected BigInteger mtotalcount;
    @XmlAttribute(name = "ElapsedTime",required = true)
    protected BigInteger melapsedTime;
    @XmlAttribute(name = "count",required = true)
    protected BigInteger count;
    @XmlAttribute(name = "totalcount",required = true)
    protected BigInteger totalcount;
    @XmlAttribute(name = "elapsedtime",required = true)
    protected BigInteger elapsedTime;

    public BigInteger getCount() {
        return count;
    }

    public void setCount(BigInteger count) {
        this.count = count;
    }

    public BigInteger getTotalcount() {
        return totalcount;
    }

    public void setTotalcount(BigInteger totalcount) {
        this.totalcount = totalcount;
    }

    public BigInteger getElapsedTime() {
        return elapsedTime;
    }

    public void setElapsedTime(BigInteger elapsedTime) {
        this.elapsedTime = elapsedTime;
    }

    public BigInteger getMcount() {
        return mcount;
    }

    public void setMcount(BigInteger mcount) {
        this.mcount = mcount;
    }

    public BigInteger getMtotalcount() {
        return mtotalcount;
    }

    public void setMtotalcount(BigInteger mtotalcount) {
        this.mtotalcount = mtotalcount;
    }

    public BigInteger getMelapsedTime() {
        return melapsedTime;
    }

    public void setMelapsedTime(BigInteger melapsedTime) {
        this.melapsedTime = melapsedTime;
    }

    /**
     * Gets the value of the cityElem property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cityElem property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCityElem().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitiesElemXML.CityElem }
     *
     *
     */
    public List<CitiesElemXML.CityElem> getCityElem() {
        if (cityElem == null) {
            cityElem = new ArrayList<CitiesElemXML.CityElem>();
        }
        return this.cityElem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "country",
        "state",
        "city"
    })
    public static class CityElem {

        @XmlElement(name = "Country", required = true)
        protected String country;
        @XmlElement(name = "State", required = true)
        protected String state;
        @XmlElement(name = "City", required = true)
        protected String city;

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

    }

}
